### ISSUE TITLE
print_board format unclear

### ISSUE THREAD

**Issue by Carroll** [hvds/seq#1]
Could you add a comment explaining how to recover the board achieved from the print_board function?

**Comment by hvds** [comment]
Sure, would this be enough to make it clear?
```
/*
 * Show the board, along with some relevant parameters.
 * Unconnected groups are separated by '  //  '; within a group the rows
 * are separated by ';', and empty spaces are represented by 0.
 */
```

**Comment by Carroll** [comment]
Yes thank you, that would be perfect.
I did not notice you had to scroll up quite a bit to see the last best or ebest (equally best) board...

**Comment by hvds** [comment]
No problems, now pushed.
